// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelUpdate() {
  return window['go']['main']['App']['CancelUpdate']();
}

export function CheckPrerequisites() {
  return window['go']['main']['App']['CheckPrerequisites']();
}

export function GetDefaults() {
  return window['go']['main']['App']['GetDefaults']();
}

export function IsUpdating() {
  return window['go']['main']['App']['IsUpdating']();
}

export function StartUpdate() {
  return window['go']['main']['App']['StartUpdate']();
}
