// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelUpdate():Promise<boolean>;

export function CheckPrerequisites():Promise<main.PrereqStatus>;

export function GetDefaults():Promise<main.Defaults>;

export function IsUpdating():Promise<boolean>;

export function StartUpdate():Promise<string>;
